import Role from './Role';
import Emoji from './Emoji';
import Channel from './Channel';
import VoiceState from './VoiceState';
import GuildMember from './GuildMember';
import PresenceUpdate from './PresenceUpdate';
export default class {
    id: string;
    name: string;
    icon: string;
    splash: string;
    discoverySplash: string;
    owner: boolean;
    ownerID: string;
    permissions: number;
    region: string;
    afkChannel: Channel;
    afkTimeout: number;
    embedEnabled: boolean;
    embedChannel: Channel;
    verificationLevel: number;
    defMessageNotify: number;
    explicitContentFilter: number;
    roles: Array<Role>;
    emojis: Array<Emoji>;
    features: Array<string>;
    mfaLevel: number;
    applicationID: string;
    widgetEnabled: boolean;
    widgetChannel: Channel;
    systemChannel: Channel;
    rulesChannel: Channel;
    joinedAt: number;
    large: boolean;
    unavailable: boolean;
    memberCount: number;
    voiceStates: Array<VoiceState>;
    members: Array<GuildMember>;
    channels: Array<Channel>;
    presences: Array<PresenceUpdate>;
    maxPresences: number;
    maxMembers: number;
    vanityURL: string;
    description: string;
    banner: string;
    premiumTier: number;
    premiumSubCount: number;
    preferredlocale: string;
    updatesChannel: Channel;
    maxChannelUsers: number;
    approxMemberCount: number;
    approxPresenceCount: number;
    constructor(id: string, name: string, icon: string, splash: string, discoverySplash: string, owner: boolean, ownerID: string, permissions: number, region: string, afkChannel: Channel, afkTimeout: number, embedEnabled: boolean, embedChannel: Channel, verificationLevel: number, defMessageNotify: number, explicitContentFilter: number, roles: Array<Role>, emojis: Array<Emoji>, features: Array<string>, mfaLevel: number, applicationID: string, widgetEnabled: boolean, widgetChannel: Channel, systemChannel: Channel, rulesChannel: Channel, joinedAt: number, large: boolean, unavailable: boolean, memberCount: number, voiceStates: Array<VoiceState>, members: Array<GuildMember>, channels: Array<Channel>, presences: Array<PresenceUpdate>, maxPresences: number, maxMembers: number, vanityURL: string, description: string, banner: string, premiumTier: number, premiumSubCount: number, preferredlocale: string, updatesChannel: Channel, maxChannelUsers: number, approxMemberCount: number, approxPresenceCount: number);
}
