name: Build
on:
  pull_request:
    branches: [development]
  push:
    branches: [development]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm i
      - run: npm start
