name: Run Tests
on:
  pull_request:
    branches: [development]
  push:
    branches: [development]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Tests
        run: npm i && tsc && cd tests && tsc && node dist/builder
        env:
          DISCORD_TOKEN: ${{secrets.BOT_TOKEN}}
